# Spring application properties
spring:
  jpa:
    database: mysql
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true

  # Data base properties
  datasource:
    url: "jdbc:mysql://172.16.15.104:3306/sellist?useSSL=false&zeroDateTimeBehavior=convertToNull&noAccessToProcedureBodies=true&sessionVariables=wait_timeout=600&serverTimezone=Asia/Seoul"
    username: "wanpan"
    password: "wanpan33"
    hikari:
      maximum-pool-size: 30
      minimum-idle: 2
      idle-timeout: 60000
      max-lifetime: 300000
      pool-name: hikari-cp


# Engine server properties
server:
  port: 8080


logging:
  file.name: sellist-engine
  level:
    org.hibernate: info
    org.springframework.web: debug
    jdbc:
      sqltiming: 'off'
      audit: 'off'
      connection: 'off'
      resultset: 'off'
      resultsettable: 'off'
      sqlonly: debug
    com.wanpan: debug


#aws:
#  credential:
#    access-key: "AKIA2LUXHOXNMRNCTL5A"
#    secret-key: "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"
#  region: ap-northeast-2
#  bucket:
#    bucket-name: "sellist-thumb"
#    prefix: "images/origin/"


internal:
  client:
    url: "172.16.15.102:8080/v1"


external:
  reebonz:
    url: "http://dev.reebonz.co.kr:3007/api"


security:
  shop-account.encrypt:
    password: "wanpan33"
    key-path: "key/receiver_keystore.p12"
    alias: "wanpan-dev"
    keystore-type: "PKCS12"
    cipher-transformation: "RSA"


gorda:
  client:
    url: "https://api.gordastyle.com"
    seller-url: "https://seller-api.gordastyle.com"
